- .flowconfig
- swapi/src/schema/__tests__/apiHelper.js
- swapi/src/schema/__tests__/film.js
- swapi/src/schema/__tests__/person.js
- swapi/src/schema/__tests__/planet.js
- swapi/src/schema/__tests__/species.js
- swapi/src/schema/__tests__/starship.js
- swapi/src/schema/__tests__/vehicle.js
- swapi/src/schema/apiHelper.js
- swapi/src/schema/connections.js
- swapi/src/schema/schema.js
- swapi/src/schema/types/film.js
- swapi/src/schema/types/person.js
- swapi/src/schema/types/planet.js
- swapi/src/schema/types/species.js
- swapi/src/schema/types/starship.js
- swapi/src/schema/types/vehicle.js
The connections in this repo are designed to allow efficient pagination
by associating cursors with each item in a connection:
```graphql
{
allPeople {
edges {
cursor
node {
name
}
}
}
}
```
When quickly exploring the API, though, it can be useful to have a shortcut
to just get the list of objects:
```graphql
{
allPeople {
people {
name
}
}
}
```
While this shortcut would not allow for the efficient cursor-based pagination
that Relay and other clients might implement, it's quite convenient for browsing
the API.
To clarify naming once that shortcut is added, each field that returns a
connection is renamed:
```graphql
{
personConnection {
people {
name
}
}
}
```
Finally, it's useful to have a total count of the number of items in each
connections, so that field is added:
```graphql
{ …
```
> Clarify connections with naming, count field, and convenience field

- src/schema/__tests__/planet.js
Before:
```
1) Planet type Gets all properties:
AssertionError: expected { Object (name, diameter, ...) } to deeply equal { Object (climates, diameter, ...) }
+ expected - actual
}
"rotationPeriod": 23
"surfaceWater": 1
"terrains": [
-    "desert"
+    "dessert"
]
}
at Assertion.assertEqual (node_modules/chai/lib/chai/core/assertions.js:485:19)
at Assertion.ctx.(anonymous function) [as equal] (node_modules/chai/lib/chai/utils/addMethod.js:41:25)
at Object.callee$1$0$ (src/schema/__tests__/planet.js:87:40)
at tryCatch (node_modules/babel-runtime/regenerator/runtime.js:72:40)
at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-runtime/regenerator/runtime.js:334:22)
at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] …
```
> Fixing "Planet type Gets all properties" Test Assertions

- package.json
`npm run start` was broken, reporting:
You have mistakenly installed the `babel` package, which is a no-op
in Babel 6. Babel's CLI commands have been moved from the `babel`
package to the `babel-cli` package.
Install `babel-cli`, making `npm run start` work again.
> Fix broken `npm run start` by adding missing babel-cli package

- package.json
- scripts/build-public
- src/public/index.html
- src/public/schema-proxy.js
- src/public/swapi.js
- src/server/main.js
Consists of:
- Simple index.html file.
- Main app bundle that loads dependencies ("react", "react-dom", "graphiql") and renders GraphiQL.
- "schema" bundle that exposes the app schema, "graphql" executor, and cached data; this is loaded separately from within the GraphiQL fetcher callback.
The main app bundle is about 56KB in size (15KB gzipped) and the schema/data bundle is 1.0MB (152KB gzipped).
I'll have follow-up commits to this, including a script that actually deploys to the gh-pages branch, but first I have to investigating whether there'll be any conflict with our existing gh-pages for graphql.github.io.
> Add ability to run from static files

- README.md
- package.json
- scripts/deploy-public
This runs the static build then commits the result to the `gh-pages` branch.
Once pushed, it will be live at: http://graphql.github.io/swapi-graphql
I checked how this works with our other organization repos. It works fine for the main graphql.github.io repo to write the files into the root of domain, and other repos will wind up in sub-directories; as long as the directory names don't conflict, everything should be fine.
> Add deploy script

- README.md
When you `npm run start`, you actually get a semi-randomly-assigned port number and will see it in the console like so:
Listening at http://localhost:51086
You'll get a different port number each time; on three runs, I got 51086, 51364 and 51525.
> Clarify port number in the README

- README.md
If you go to graphql.github.io you're going to get redirected anyway, so we may as well use the shorter link and avoid the extra hop.
> Shorten demo URL in readme

- scripts/watch.js
Was choking on ES6 stuff while running tests, but no longer so.
> Fix `npm run watch`

- .babelrc
- package.json
- src/public/schema-proxy.js
- src/schema/connections.js
- src/schema/relayNode.js
I suspect these came in with the last Flow upgrade (f0e690550afef50c4346, which put us on v0.38.0), which is stricter about some things.
> Fix Flow errors

- scripts/download
This should allow the `npm run download` to work on a wider range of `node` versions (ie. lacking `let`/`const` support etc).
Closes: https://github.com/graphql/swapi-graphql/issues/50
> Perform download with babel-node

- package.json
- yarn.lock
Greenkeeper was complaining about these updates here:
- https://github.com/graphql/swapi-graphql/issues/56
- https://github.com/graphql/swapi-graphql/issues/57
I fixed the underlying issue here:
- https://github.com/graphql/swapi-graphql/pull/58
So we should be good to go with these updates now.
> Apply updates that Greenkeeper was complaining about

- src/api/cachedData/downloadCache.js
- src/schema/__tests__/film.js
- src/schema/__tests__/person.js
- src/schema/__tests__/planet.js
- src/schema/__tests__/species.js
- src/schema/__tests__/starship.js
- src/schema/__tests__/vehicle.js
- src/schema/apiHelper.js
- src/schema/types/person.js
- src/schema/types/planet.js
- src/schema/types/species.js
- src/schema/types/starship.js
- src/schema/types/vehicle.js
We plan to release our new library and want to use SWAPI proxy in examples.
During testing I discovered multiple valid queries that produce errors, here is just a few examples:
@wincent Can you please review these fixes?
> Fix for multiple errors related to data conversion

- src/schema/__tests__/film.js
- src/schema/__tests__/person.js
- src/schema/__tests__/planet.js
- src/schema/__tests__/species.js
- src/schema/__tests__/starship.js
- src/schema/__tests__/vehicle.js
This is still using string interpolation to build the document, but fragments are "the right way" to share selections across queries, so this is better.
Follow-up to: https://github.com/graphql/swapi-graphql/pull/87
> Use fragments for re-use in specs

- src/api/cachedData/downloadCache.js
Add a check to see if the "reverse" linked item already exists rather than blindly `push`-ing it.
Closes: #120
> Avoid duplicate entries in connections

- src/schema/types/starship.js
- src/schema/types/vehicle.js
There is an inconsistency in types between `starship` and `vehicle`.
The `cargoCapacity` and `costInCredits` are typed as float for `starship` and as int for `vehicle`.
This PR will standardize the types between `starship` and `vehicle` and change those fields type to be float.
In fact, those values are int but the cargo capacity of the Death Star is too big for an int, so to ensure that the tests passes, we have to use float.
> Standardize types between vehicles and starships

- public/index.html
i think it issues a 301 or some such, so possibly a few 30-50ms extra roundtrip, but worth it to have the latest npm release always, no? maybe using the new min.css will make up for it?
> use latest release for cdn bundles

- handler/swapi.js
- scripts/download.js
- scripts/mocha-bootload.js
- scripts/print-schema.js
- scripts/serve-public.js
- scripts/store-schema.js
- scripts/watch.js
- src/swapi-rest.js
* update swapi datasource. swapi.co seems gone. changed it to raw github json in a repo thats bene updated ~2yago at least
* add a swapi REST netlify demo, why not?
* some copyright changes, more soon
> chore: update swapi datasource, add swapi rest

- README.md
- app.json
- package.json
- src/api/__tests__/local.js
- src/schema/__tests__/apiHelper.js
- src/schema/apiHelper.js
This finishes it out, other than the http rewrite to https in the last commit, this should do it
> fix: fully switch from swapi.co to swapi.dev

- src/schema/__tests__/apiHelper.js
- src/schema/__tests__/film.js
- src/schema/__tests__/person.js
- src/schema/__tests__/planet.js
- src/schema/__tests__/species.js
- src/schema/__tests__/starship.js
Tests assertion values were little out of sync from what SWAPI returned so updated those values.
Note: Use `yarn cover` to run tests because `yarn test` fails at the moment because Flow is broken. Also `yarn coveralls` isn't working and will fix it once we switch to NPM #180 and update deps
> Update tests to match swapi.dev

- netlify.toml
This PR fixes the Netlify integration that currently fails when trying to use file `cache/data.json` in the build process. 
fixes #183
> fixing Netlify integration

- schema.graphql
- scripts/deploy-public
- scripts/download.js
- src/schema/types/planet.js
This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/swapi-graphql/commit/f5467becd4726c0bd4d5b495a8ff6295ee89e4ca#commitcomment-55983818
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/swapi-graphql/commit/eca392c78c1f1939d12b3ddc68952dd3ea52976e
Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.
> Fix spelling

- public/index.html
This PR changes the `index.html` so that it creates the fetcher function using `GraphiQL.createFetcher`. This should fix the issue that headers entered in the headers editor are not sent with the GraphQL request, (see https://github.com/graphql/graphiql/issues/2707).
Also prettified the file (sorry for the messy diff 🙈 )
> use `createGraphiQLFetcher` to fix missing headers

- handler/index.mjs
- handler/swapi.mjs
Currently the graphql site reaches out to this URL and will be redirected. However the OPTIONS request will fail as that can't be redirected so to do this successfully we'll need to combine this with a successful options request.
> Handle redirects in other routes

- README.md
- app.json
- package-lock.json
- package.json
- scripts/download.js
- src/api/__tests__/local.spec.js
- src/schema/__tests__/apiHelper.spec.js
- src/schema/apiHelper.js
- src/schema/constants.js
- sometimes we get `data.result` or `data.results`
- sometimes we get `obj.properties` or just `obj`
- sometimes the domains are inconsistent (www. or root)
- in some cases, we are missing data with the new datasource, such as `starship.pilots` (and thus `character.starships`)
I fixed it as readily as possible in download, and "patched" it at API resolution
using this query for testing
```graphql
{
allFilms {
edges {
node {
id
title
characterConnection {
characters {
id
name
}
}
}
}
}
film(filmID: 6) {
id
title
}
allStarships {
edges {
node {
id
name
pilotConnection {
pilots {
id
name
}
}
}
}
}
film(filmID: 6) {
id
title
}
}
```
the long term solution is to build our own static datasource in a typescript file, as the json is quite repetetive and cumbersome. I will work on this after we …
> fix: swapi.tech execution by normalizing as best as possible

- package-lock.json
- package.json
This fixes our missing headers, which is fixed in https://github.com/graphql/graphql-http/commit/cd1523f261946b97f0237444802fea760752b767
> Bump graphql-http
